# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Personal Jekyll Test Site
email: matty@thestrangeland.net
description: > # this means to ignore newlines until "baseurl:"
  This is a personal site for Matt McGraw to learn Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://g33kdad.github.io" # the base hostname & protocol for your site
twitter_username: sahg33kdad
github_username:  g33kdad

# Build settings
markdown: kramdown
